CONJUNTOS


In [6]:
conjunto1={1,2,2,3,3,4}
conjunto2={3,4,5,6}


In [7]:
type(conjunto1)

set

In [8]:
conjunto1

{1, 2, 3, 4}

In [9]:
dir(conjunto1)

['__and__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iand__',
 '__init__',
 '__init_subclass__',
 '__ior__',
 '__isub__',
 '__iter__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__or__',
 '__rand__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__ror__',
 '__rsub__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__xor__',
 'add',
 'clear',
 'copy',
 'difference',
 'difference_update',
 'discard',
 'intersection',
 'intersection_update',
 'isdisjoint',
 'issubset',
 'issuperset',
 'pop',
 'remove',
 'symmetric_difference',
 'symmetric_difference_update',
 'union',
 'update']

INTERSECCION

In [12]:
print(conjunto1, conjunto2)

{1, 2, 3, 4} {3, 4, 5, 6}


In [13]:
conjunto1 & conjunto2 #intersección entre 2 conjuntos

{3, 4}

In [14]:
conjunto1.intersection(conjunto2)

{3, 4}

In [18]:
conjunto3={"blanco", "rojo", "azul"}
conjunto4={"rosa", "amarillo", "blanco"}


In [19]:
conjunto3&conjunto4

{'blanco'}

In [22]:
import numpy as np
arreglo=np.array(((0,1,0),
          (0,1,0), 
          (1,1,1)),dtype=np.uint8)

In [23]:
print(arreglo)

[[0 1 0]
 [0 1 0]
 [1 1 1]]


In [29]:
vecindad = arreglo[1][1]


1