int
entero:1,2,3,100,40,2



flotante: 0.2,04,10,3
booleano: true or false
str: "texto
pi: constante

para una funcion ocupamos :


In [1]:
def hola():
    print("HOLIWIS")

In [2]:
hola()

HOLIWIS


In [3]:
#suma
5+7
#resta
9-3
#multiplicacion 
10*5
#division
40/4
#division unicamente enteros
40//2 
#potencia
2**2


4

In [4]:
#concatenación
print ("10"+"5") 
print("Banana"*3)

105
BananaBananaBanana


In [5]:
print("HOLA")
type("hola")

HOLA


str

In [6]:
var = input("Ingrese un numero: ")
var

''

In [7]:
print("Hola")

Hola


In [8]:
variable =int(input("Ingrese un número: "))
type(variable)

ValueError: invalid literal for int() with base 10: ''

In [ ]:
x = "TaylorSwifT"
x.count("T")

2


CONDICIONALES

In [ ]:
print(10==10) #comparación

True


In [ ]:
print(10<10)

False


LISTAS


In [ ]:
lista =[1,"Hola",True,]

In [ ]:
len(lista)

3

In [ ]:
lista[0]

1

In [ ]:
lista.append("TaylorS")
print(lista)

[1, 'Hola', True, 'TaylorS', 'TaylorS']


In [ ]:
eliminado =lista.pop(3)
print(lista)


[1, 'Hola', True, 'TaylorS']


In [ ]:
if 10 < 100:
    print("HOLISS, SI ES MENOR")

HOLISS, SI ES MENOR


In [ ]:
if 7 < 100:
    print("hOLA SI ES MENOR")
elif 9 >100:
    print("hey hey")


hOLA SI ES MENOR


CICLO FOR


In [ ]:
for i in x:
    print(i)

T
a
y
l
o
r
S
w
i
f
T


In [ ]:
x = "abecedario"
for i in x:
    print(i, end="")

abecedario

In [ ]:
for i in range(5):
    print("Programar")

Programar
Programar
Programar
Programar
Programar


In [ ]:
listavoc = ["a", "e", "i", "o"]
for n, i in enumerate(listavoc):
    print(f"elemento: {i} in Posicion: {n}")

elemento: a in Posicion: 0
elemento: e in Posicion: 1
elemento: i in Posicion: 2
elemento: o in Posicion: 3


CICLO WHILE

In [ ]:
conteo = 0
while conteo <=5:
    print("HOY ES 12")
    conteo+=1

HOY ES 12
HOY ES 12
HOY ES 12
HOY ES 12
HOY ES 12
HOY ES 12


FUNCIONES

In [ ]:
def sumar(a,b):
    x = a+b
    return x
suma = sumar(5,10)
print(suma)


15


IF ANIDADOS

In [ ]:
a =5
b = 50
if a < b:
    print("A es menor que b")
    if (a < 100):
        print("a tambien es menor que 100")

A es menor que b
a tambien es menor que 100


FOR ANIDADOS


In [ ]:
a = [1,2,3]
b =[0,9]
for i in a:
    for j in b:
        print(i,j)

1 0
1 9
2 0
2 9
3 0
3 9


NUMPY


Trabaja con arreglos multidimensionales y matrices

MATRICES

In [ ]:
import numpy as np
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matriz)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
matriz1=np.random.random((3,3))
print(matriz1)

[[0.14315363 0.05714474 0.43541758]
 [0.71700177 0.74909955 0.22428633]
 [0.27419852 0.36817737 0.37239665]]


In [ ]:
import numpy as np
matrix = np.arange(15, dtype=np.int64).reshape((3,5))
print(matrix)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
matrix[1,3]
#muestra el elemento en estas coordenadas

8

metodo max

In [ ]:
import numpy as np
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
mat.max

<function ndarray.max>

In [ ]:
x = np.arange(15, dtype=np.float64).reshape(3,5)
print(x)

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]]


In [ ]:
np.max(x)
#valor máximo de la matriz

14.0

In [ ]:
np.max(x, axis=0)
#valor maximo en el eje x

array([10., 11., 12., 13., 14.])

In [ ]:
np.min(x)

0.0

In [ ]:
np.min(x, axis = 0)

array([ 0.,  5., 10.])

METODO SHAPE


In [ ]:
x.shape

(3, 5)

METODO ZEROS

In [ ]:
matrix1 = np.zeros((3,3))
print(matrix1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


METODO UNOS

In [ ]:
matrix2 = np.ones((4,4))
print(matrix2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
matriz = np.random.random((3,3))
print(matriz)

[[0.23823058 0.59685499 0.96893209]
 [0.25322473 0.46735242 0.90779111]
 [0.51409669 0.21415661 0.93764983]]


In [ ]:
matriz4= np.random.randint(10, size = (3,3))
print(matriz4)

[[3 2 0]
 [0 3 0]
 [4 5 4]]


In [ ]:
np.random.seed(123)
matriz5=np.random.randint(10, size =(3,3))
print(matriz5)

[[2 2 6]
 [1 3 9]
 [6 1 0]]


In [ ]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.where(matriz>=5)

(array([1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2]))

In [ ]:
np.arange(12).reshape((4,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

METODO MEAN


In [ ]:
x= np.arange(15, dtype=np.int64).reshape((3,5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
x.mean(axis = 0)

array([5., 6., 7., 8., 9.])

METODO ARANGE

In [ ]:
matrices = np.arange(10, dtype=np.int64).reshape((2,5))
matrices

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

MATRIZ FILA

In [ ]:
matriz6= np.array([[1,2,3]])
matriz6

array([[1, 2, 3]])

MATRIZ COLUMNA

In [ ]:
matriz7=np.array([[1],[2],[3]])
matriz7

array([[1],
       [2],
       [3]])

MATRIZ CUADRADA

In [ ]:
matriz8=np.array([[1,2,3],[4,5,6],[7,8,9]])
matriz8

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matriz8=np.arange(4, dtype=np.int8).reshape(2,2)
matriz8

array([[0, 1],
       [2, 3]], dtype=int8)

MATRIZ RECTANGULAR


In [ ]:
matriz8=np.arange(15, dtype=np.int8).reshape(3,5)
matriz8

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]], dtype=int8)

 MATRIZ IDENTIDAD

In [ ]:
matriz =np.eye(3)
matriz

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

MATRIZ TRANSPUESTA

In [ ]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
transpuesta=matriz.T
transpuesta

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
matriz1=np.array([[1,2,3],[4,5,6],[7,8,9]])
matriz1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matriz1=np.array([[1,2,3],[4,5,6],[7,8,9]])
transpuesta2=matriz1.transpose()
transpuesta2

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

OPERACIONES MATRICES-ESCALARES

MULTIPLICACION

In [ ]:
k=2
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(k*A)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


DIVISION DE UNA MATRIZ POR UNA ESCALAR

In [ ]:
k=2
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A//k)

[[0 1 1]
 [2 2 3]
 [3 4 4]]


DIVISION DE UNA ESCALAR POR UNA MATRIZ

In [ ]:
k=2
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(k//A)

POTENCIA DE UNA MATRIZ

In [ ]:
k=2
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A**k)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


RAZI DE UNA MATRIZ

In [ ]:

A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A**(1/2))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


SUMA MATRICES

In [ ]:
B=np.array([[40,50,60],[70,80,90],[10,20,30]])
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A+B)

[[41 52 63]
 [74 85 96]
 [17 28 39]]


RESTA MATRICES

In [ ]:
B=np.array([[40,50,60],[70,80,90],[10,20,30]])
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(B-A)

[[39 48 57]
 [66 75 84]
 [ 3 12 21]]


MULTIPLICACION

In [ ]:
B=np.array([[40,50,60],[70,80,90],[10,20,30]])
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A*B)

[[ 40 100 180]
 [280 400 540]
 [ 70 160 270]]


INVERSA

In [ ]:
arr=np.array([[1,3,5],[5,7,7],[9,11,87]])
inversa=np.linalg.inv(arr)
print(inversa)

[[-0.8525641   0.33012821  0.0224359 ]
 [ 0.59615385 -0.06730769 -0.02884615]
 [ 0.01282051 -0.02564103  0.01282051]]
